import { Box, Button, Text } from '@chakra-ui/react';
import Head from 'next/head';
import { useState } from 'react';

const data = {};

export default function Home() {
  const [simulateError, setSimulateError] = useState(false);

  const onSimulateError = () => {
    setSimulateError(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px="50px">
        <Text fontSize="4xl">Hello world!</Text>

        <Button colorScheme="blue" onClick={onSimulateError}>
          Simulate error
        </Button>

        {simulateError && <Text>{data.a.b}</Text>}
      </Box>
    </>
  );
}
